### ISSUE TITLE
Make level loading dynamic from a file

### ISSUE THREAD

**Issue by jamesaorson** [brandonapol/basement-escape#4]
I do not want to have to edit your code to have a new level

Consider that I was using this library as a package.

How could you get the same functionality, but taken as a dynamic object that you could accept as input?

**Comment by brandonapol** [comment]
I like this idea, but I don't want to make it a super-public repo, just a thing for a specific audience. I could add them manually to a private repo, but I want them to participate, so I'm just going to leave it like this for now

**Comment by jamesaorson** [comment]
I mean, you can basically copy paste your dict into a Json file and load that and call it a day
